// currencyToCountry.ts
// Map currency codes to country codes for flag rendering

const currencyToCountry: Record<string, string> = {
  USD: 'US',
  EUR: 'EU',
  GBP: 'GB',
  JPY: 'JP',
  AUD: 'AU',
  CAD: 'CA',
  CHF: 'CH',
  CNY: 'CN',
  HKD: 'HK',
  NZD: 'NZ',
  SEK: 'SE',
  KRW: 'KR',
  SGD: 'SG',
  NOK: 'NO',
  MXN: 'MX',
  INR: 'IN',
  RUB: 'RU',
  ZAR: 'ZA',
  TRY: 'TR',
  BRL: 'BR',
  TWD: 'TW',
  DKK: 'DK',
  PLN: 'PL',
  THB: 'TH',
  IDR: 'ID',
  HUF: 'HU',
  CZK: 'CZ',
  ILS: 'IL',
  CLP: 'CL',
  PHP: 'PH',
  AED: 'AE',
  COP: 'CO',
  SAR: 'SA',
  MYR: 'MY',
  RON: 'RO',
  XAF: 'CM',
  XOF: 'SN',
  XCD: 'LC',
  XPF: 'PF',
  XCG: 'CW',
}

export default currencyToCountry
